name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build --platform linux/amd64 -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:${{ github.sha }}
        docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:latest
    
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:latest
        containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
