name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build --platform linux/amd64 -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:${{ github.sha }}
        docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:latest
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Enable dynamic extension install in Azure CLI
      run: az config set extension.use_dynamic_install=yes_without_prompt
      
    - name: Deploy to Azure Container App
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/next-azure-poc:latest
